# https://github.com/dorny/paths-filter
python:
  - "src/backend/**"
  - "src/backend/**.py"
  - "pyproject.toml"
  - "poetry.lock"
  - "**/python_test.yml"
components-changes:
  - "src/backend/base/langflow/components/**"
starter-projects-changes:
  - "src/backend/base/langflow/initial_setup/**"
frontend-tests:
  - "src/frontend/tests/**"
frontend:
  - "src/frontend/**"
  - "**/typescript_test.yml"
docs:
  - "docs/**"
# Test categories and their associated paths
components:
  - "src/frontend/src/components/**"
  - "!src/frontend/src/components/starterProjects/**"

starter-projects:
  - "src/frontend/src/components/starterProjects/**"
  - "src/backend/base/langflow/initial_setup/**"
  - "src/frontend/workspace/starterProjects/**"

workspace:
  - "src/frontend/workspace/**"
  - "src/frontend/src/pages/workspace/**"
  - "src/frontend/src/components/workspace/**"
  - "src/frontend/src/components/ui/renderInputParameter/**"
  - "src/frontend/src/components/outputInspection/**"
  - "src/frontend/src/components/playground/**"

api:
  - "src/backend/base/langflow/api/**"
  - "src/frontend/src/api/**"

database:
  - "src/backend/base/langflow/services/database/**"
  - "src/backend/base/langflow/alembic/**"
  - "src/frontend/src/services/database/**"

release:
  - "src/frontend"
  - "src/backend"
