services:
  # A Docker web service
  - type: web
    name: instro-backend
    runtime: docker
    dockerfilePath: ./docker/instro.Dockerfile
    repo: https://github.com/InstroAISolutions/langflow
    branch: production
    plan: standard
    region: frankfurt
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: postgresql://langflow_poc_vcal_user:0ab9dLTAvmMUXfimflbgP6VRDUFcdpt7@dpg-csrpm752ng1s73ac1fbg-a.frankfurt-postgres.render.com:5432/langflow_poc_vcal
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        value: 10000
      - key: LANGFLOW_LOG_LEVEL
        value: ERROR
      - key: LANGFLOW_SUPERUSER
        value: instro
      - key: LANGFLOW_SUPERUSER_PASSWORD
        value: 6p^m8jh5Z-Zjfu           
      - key: LANGFLOW_AUTO_LOGIN
        value: false